using RockSniffer.Addons.Storage;
using RockSniffer.Configuration;
using RockSnifferLib.Sniffing;
using System;
using System.IO;
using System.Net;

namespace RockSniffer.Addons
{
    internal class AddonService
    {
#if DEBUG
        internal static readonly string addonsPath = "../../../../addons";
#else
        internal static readonly string addonsPath = "./addons";
#endif

        private AddonServiceListener listener;

        public AddonService(AddonSettings settings, IAddonStorage storage)
        {
            if (!IPAddress.TryParse(settings.ipAddress, out IPAddress ip))
            {
                throw new Exception($"IP Address '{settings.ipAddress}' is not valid");
            }

            Console.WriteLine("Starting AddonService listener on {0}:{1}", ip.ToString(), settings.port);

            GenerateConfig(settings);

            listener = new AddonServiceListener(ip, settings, storage);
        }

        private void GenerateConfig(AddonSettings settings)
        {
            // Generate a config js file that addons can use, to make configuring 2pc setup addons less painful
            string pattern = $@"// THIS FILE IS AUTOMATICALLY GENERATED

// Sniffer addon service connection details
var ip = ""{settings.ipAddress}"";
var port = {settings.port};
            ";

            var configPath = Path.Combine(addonsPath, "config.js");

            File.WriteAllText(configPath, pattern);
        }

        public void SetSniffer(Sniffer sniffer)
        {
            sniffer.OnSongChanged += listener.OnCurrentSongChanged;
            sniffer.OnMemoryReadout += listener.OnMemoryReadout;
            sniffer.OnStateChanged += listener.OnStateChanged;
        }
    }
}
