using RockSniffer.Addons.Storage;
using RockSniffer.Configuration;
using RockSnifferLib.Sniffing;
using System;
using System.IO;
using System.Net;

namespace RockSniffer.Addons
{
    internal class AddonService
    {
        internal static string AddonsPath { get; private set; }

        private AddonServiceListener listener;

        public AddonService(AddonSettings settings, IAddonStorage storage)
        {
            if (!IPAddress.TryParse(settings.ipAddress, out IPAddress ip))
            {
                throw new Exception($"IP Address '{settings.ipAddress}' is not valid");
            }

            Console.WriteLine("Starting AddonService listener on {0}:{1}", ip.ToString(), settings.port);

            // If addons folder was found, auto generate config file
            if (FindAddons())
            {
                GenerateConfig(settings);
            }
            else
            {
                Console.WriteLine("Addons folder not found, skipped config.js generation");
            }

            listener = new AddonServiceListener(ip, settings, storage);
        }

        /// <summary>
        /// Try to find the addons folder
        /// </summary>
        private bool FindAddons()
        {
            var path = "./addons";

            if (Directory.Exists(path))
            {
                AddonsPath = path;
                return true;
            }
#if DEBUG // Find addons from the git root, if running in debug mode for development
            path = "../../../../addons";
            if (Directory.Exists(path))
            {
                AddonsPath = path;
                return true;
            }
#endif

            return false;
        }

        private void GenerateConfig(AddonSettings settings)
        {
            // Generate a config js file that addons can use, to make configuring 2pc setup addons less painful
            string pattern = $@"// THIS FILE IS AUTOMATICALLY GENERATED

// Sniffer addon service connection details
var ip = ""{settings.ipAddress}"";
var port = {settings.port};
            ";

            var configPath = Path.Combine(AddonsPath, "config.js");

            File.WriteAllText(configPath, pattern);
        }

        public void SetSniffer(Sniffer sniffer)
        {
            sniffer.OnSongChanged += listener.OnCurrentSongChanged;
            sniffer.OnMemoryReadout += listener.OnMemoryReadout;
            sniffer.OnStateChanged += listener.OnStateChanged;
        }
    }
}
